Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/guides/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/guides/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/guides/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/guides/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/guides/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/guides/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/guides/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## importantly each element of this iterable can be navigated like the whole tree did
tbody = soup.find_all('tbody')[0]
for tr in tbody.find_all('tr')[1:]: ## the first element (0th in the list) is the columns names, so I have gotten rid of it
    # print(tr)
    # print('_________')
    row = tr.find_all(['td','th'])
    print(row[0].a['href'], row[1].b.get_text(), row[1].small.get_text(), row[2].get_text(), row[3].get_text(), row[4].get_text(), sep='\n')
    print('_________')
## now we're getting somewhere
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 7[0m
[1;32m      3[0m [38;5;28;01mfor[39;00m tr [38;5;129;01min[39;00m tbody[38;5;241m.[39mfind_all([38;5;124m'[39m[38;5;124mtr[39m[38;5;124m'[39m)[[38;5;241m1[39m:]: [38;5;66;03m## the first element (0th in the list) is the columns names, so I have gotten rid of it[39;00m
[1;32m      4[0m     [38;5;66;03m# print(tr)[39;00m
[1;32m      5[0m     [38;5;66;03m# print('_________')[39;00m
[1;32m      6[0m     row [38;5;241m=[39m tr[38;5;241m.[39mfind_all([[38;5;124m'[39m[38;5;124mtd[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mth[39m[38;5;124m'[39m])
[0;32m----> 7[0m     [38;5;28mprint[39m(row[[38;5;241m0[39m][38;5;241m.[39ma[[38;5;124m'[39m[38;5;124mhref[39m[38;5;124m'[39m], row[[38;5;241m1[39m][38;5;241m.[39mb[38;5;241m.[39mget_text(), [43mrow[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[38;5;241;43m.[39;49m[43msmall[49m[38;5;241;43m.[39;49m[43mget_text[49m(), row[[38;5;241m2[39m][38;5;241m.[39mget_text(), row[[38;5;241m3[39m][38;5;241m.[39mget_text(), row[[38;5;241m4[39m][38;5;241m.[39mget_text(), sep[38;5;241m=[39m[38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m)
[1;32m      8[0m     [38;5;28mprint[39m([38;5;124m'[39m[38;5;124m_________[39m[38;5;124m'[39m)
[1;32m      9[0m [38;5;66;03m## now we're getting somewhere[39;00m

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'get_text'

